# Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 6', carrier: "Other Carrier", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 6', carrier: "Other Carrier", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 6', carrier: "Other Carrier", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 300)
# Product.create(model: 'iPhone 5', carrier: "Other Carrier", capacity: 16, condition: "busted", price: 200)
# Product.create(model: 'iPhone 5', carrier: "Other Carrier", capacity: 16, condition: "fair", price: 250)
# Product.create(model: 'iPhone 5', carrier: "Other Carrier", capacity: 16, condition: "pristine", price: 300)

Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 6', carrier: "Other Carrier", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 6', carrier: "Other Carrier", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 6', carrier: "Other Carrier", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 32, condition: "pristine", price: 300)
Product.create(model: 'iPhone 5', carrier: "Other Carrier", capacity: 32, condition: "busted", price: 200)
Product.create(model: 'iPhone 5', carrier: "Other Carrier", capacity: 32, condition: "fair", price: 250)
Product.create(model: 'iPhone 5', carrier: "Other Carrier", capacity: 32, condition: "pristine", price: 300)