Sale.create(email: "test@test.com")
Superuser.create(email: "bar@bar.com", password: "barbar")
Superuser.create(email: "Marc@sellible.com", password: "runner169")
Superuser.create(email: "Daniel@sellible.com", password: "Daphil88")




Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 16, condition: "busted", price: 100 )
Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 16, condition: "fair", price: 100)
Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 16, condition: "pristine", price: 100)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 16, condition: "busted", price: 160) 
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 16, condition: "fair", price: 290)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 16, condition: "pristine", price: 325)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 220)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 245)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 16, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 16, condition: "fair", price: 220)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 16, condition: "pristine", price: 245)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 16, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 16, condition: "fair", price: 290)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 325)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 16, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 16, condition: "fair", price: 250)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 16, condition: "pristine", price: 280)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 16, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 16, condition: "fair", price: 260)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 16, condition: "pristine", price: 290)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 180)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 205)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 16, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 16, condition: "fair", price: 180)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 16, condition: "pristine", price: 285)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 16, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 16, condition: "fair", price: 260)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 290)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 16, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 16, condition: "fair", price: 125)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 16, condition: "pristine", price: 150)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 16, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 16, condition: "fair", price: 130)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 16, condition: "pristine", price: 155)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 85)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 100)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 16, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 16, condition: "fair", price: 85)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 16, condition: "pristine", price: 100)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 16, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 16, condition: "fair", price: 135)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 160)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 16, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 16, condition: "fair", price: 70)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 16, condition: "pristine", price: 90)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 16, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 16, condition: "fair", price: 70)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 16, condition: "pristine", price: 90)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 45)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 55)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 16, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 16, condition: "fair", price: 45)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 16, condition: "pristine", price: 55)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 16, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 16, condition: "fair", price: 80)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 100)
Product.create(model: 'iPhone 5c', carrier: "ATT", capacity: 16, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "ATT", capacity: 16, condition: "fair", price: 70)
Product.create(model: 'iPhone 5c', carrier: "ATT", capacity: 16, condition: "pristine", price: 80)
Product.create(model: 'iPhone 5c', carrier: "Verizon", capacity: 16, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "Verizon", capacity: 16, condition: "fair", price: 70)
Product.create(model: 'iPhone 5c', carrier: "Verizon", capacity: 16, condition: "pristine", price: 80)
Product.create(model: 'iPhone 5c', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 25)
Product.create(model: 'iPhone 5c', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 30)
Product.create(model: 'iPhone 5c', carrier: "Sprint", capacity: 16, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "Sprint", capacity: 16, condition: "fair", price: 25)
Product.create(model: 'iPhone 5c', carrier: "Sprint", capacity: 16, condition: "pristine", price: 30)
Product.create(model: 'iPhone 5c', carrier: "Unlocked", capacity: 16, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "Unlocked", capacity: 16, condition: "fair", price: 75)
Product.create(model: 'iPhone 5c', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 85)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 16, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 16, condition: "fair", price: 20)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 16, condition: "pristine", price: 25)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 16, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 16, condition: "fair", price: 20)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 16, condition: "pristine", price: 25)
Product.create(model: 'iPhone 4s', carrier: "T-Mobile", capacity: 16, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "T-Mobile", capacity: 16, condition: "fair", price: 10)
Product.create(model: 'iPhone 4s', carrier: "T-Mobile", capacity: 16, condition: "pristine", price: 15)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 16, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 16, condition: "fair", price: 10)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 16, condition: "pristine", price: 15)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 16, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 16, condition: "fair", price: 25)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 16, condition: "pristine", price: 30)






Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 32, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 32, condition: "fair", price: 130)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 32, condition: "pristine", price: 155)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 32, condition: "busted", price: 40)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 32, condition: "fair", price: 75)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 32, condition: "pristine", price: 95)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 32, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 32, condition: "fair", price: 90)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 32, condition: "pristine", price: 105)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 32, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 32, condition: "fair", price: 90)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 32, condition: "pristine", price: 105)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 32, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 32, condition: "fair", price: 140)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 32, condition: "pristine", price: 165)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 32, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 32, condition: "fair", price: 75)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 32, condition: "pristine", price: 95)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 32, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 32, condition: "fair", price: 75)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 32, condition: "pristine", price: 95)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 32, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 32, condition: "fair", price: 50)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 32, condition: "pristine", price: 60)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 32, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 32, condition: "fair", price: 50)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 32, condition: "pristine", price: 60)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 32, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 32, condition: "fair", price: 85)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 32, condition: "pristine", price: 105)
Product.create(model: 'iPhone 5c', carrier: "ATT", capacity: 32, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "ATT", capacity: 32, condition: "fair", price: 75)
Product.create(model: 'iPhone 5c', carrier: "ATT", capacity: 32, condition: "pristine", price: 85)
Product.create(model: 'iPhone 5c', carrier: "Verizon", capacity: 32, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "Verizon", capacity: 32, condition: "fair", price: 75)
Product.create(model: 'iPhone 5c', carrier: "Verizon", capacity: 32, condition: "pristine", price: 85)
Product.create(model: 'iPhone 5c', carrier: "T-Mobile", capacity: 32, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "T-Mobile", capacity: 32, condition: "fair", price: 30)
Product.create(model: 'iPhone 5c', carrier: "T-Mobile", capacity: 32, condition: "pristine", price: 35)
Product.create(model: 'iPhone 5c', carrier: "Sprint", capacity: 32, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "Sprint", capacity: 32, condition: "fair", price: 30)
Product.create(model: 'iPhone 5c', carrier: "Sprint", capacity: 32, condition: "pristine", price: 35)
Product.create(model: 'iPhone 5c', carrier: "Unlocked", capacity: 32, condition: "busted", price: 20)
Product.create(model: 'iPhone 5c', carrier: "Unlocked", capacity: 32, condition: "fair", price: 80)
Product.create(model: 'iPhone 5c', carrier: "Unlocked", capacity: 32, condition: "pristine", price: 90)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 32, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 32, condition: "fair", price: 25)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 32, condition: "pristine", price: 30)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 32, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 32, condition: "fair", price: 25)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 32, condition: "pristine", price: 30)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 32, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 32, condition: "fair", price: 15)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 32, condition: "pristine", price: 20)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 32, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 32, condition: "fair", price: 30)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 32, condition: "pristine", price: 35)


Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 64, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 64, condition: "fair", price: 285)
Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 64, condition: "pristine", price: 315)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 64, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 64, condition: "fair", price: 295)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 64, condition: "pristine", price: 330)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 64, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 64, condition: "fair", price: 230)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 64, condition: "pristine", price: 260)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 64, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 64, condition: "fair", price: 230)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 64, condition: "pristine", price: 260)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 64, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 64, condition: "fair", price: 295)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 64, condition: "pristine", price: 330)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 64, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 64, condition: "fair", price: 255)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 64, condition: "pristine", price: 285)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 64, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 64, condition: "fair", price: 265)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 64, condition: "pristine", price: 295)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 64, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 64, condition: "fair", price: 190)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 64, condition: "pristine", price: 215)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 64, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 64, condition: "fair", price: 190)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 64, condition: "pristine", price: 215)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 64, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 64, condition: "fair", price: 265)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 64, condition: "pristine", price: 295)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 64, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 64, condition: "fair", price: 135)
Product.create(model: 'iPhone 5s', carrier: "ATT", capacity: 64, condition: "pristine", price: 160)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 64, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 64, condition: "fair", price: 140)
Product.create(model: 'iPhone 5s', carrier: "Verizon", capacity: 64, condition: "pristine", price: 165)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 64, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 64, condition: "fair", price: 95)
Product.create(model: 'iPhone 5s', carrier: "T-Mobile", capacity: 64, condition: "pristine", price: 110)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 64, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 64, condition: "fair", price: 95)
Product.create(model: 'iPhone 5s', carrier: "Sprint", capacity: 64, condition: "pristine", price: 110)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 64, condition: "busted", price: 70)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 64, condition: "fair", price: 145)
Product.create(model: 'iPhone 5s', carrier: "Unlocked", capacity: 64, condition: "pristine", price: 170)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 64, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 64, condition: "fair", price: 80)
Product.create(model: 'iPhone 5', carrier: "ATT", capacity: 64, condition: "pristine", price: 100)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 64, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 64, condition: "fair", price: 100)
Product.create(model: 'iPhone 5', carrier: "Verizon", capacity: 64, condition: "pristine", price: 110)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 64, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 64, condition: "fair", price: 55)
Product.create(model: 'iPhone 5', carrier: "T-Mobile", capacity: 64, condition: "pristine", price: 65)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 64, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 64, condition: "fair", price: 55)
Product.create(model: 'iPhone 5', carrier: "Sprint", capacity: 64, condition: "pristine", price: 65)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 64, condition: "busted", price: 40)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 64, condition: "fair", price: 90)
Product.create(model: 'iPhone 5', carrier: "Unlocked", capacity: 64, condition: "pristine", price: 110)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 64, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 64, condition: "fair", price: 30)
Product.create(model: 'iPhone 4s', carrier: "ATT", capacity: 64, condition: "pristine", price: 35)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 64, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 64, condition: "fair", price: 30)
Product.create(model: 'iPhone 4s', carrier: "Verizon", capacity: 64, condition: "pristine", price: 35)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 64, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 64, condition: "fair", price: 20)
Product.create(model: 'iPhone 4s', carrier: "Sprint", capacity: 64, condition: "pristine", price: 25)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 64, condition: "busted", price: 5)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 64, condition: "fair", price: 35)
Product.create(model: 'iPhone 4s', carrier: "Unlocked", capacity: 64, condition: "pristine", price: 40)

Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 128, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 128, condition: "fair", price: 290)
Product.create(model: 'iPhone 6 Plus', carrier: "ATT", capacity: 128, condition: "pristine", price: 325)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 128, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 128, condition: "fair", price: 300)
Product.create(model: 'iPhone 6 Plus', carrier: "Verizon", capacity: 128, condition: "pristine", price: 335)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 128, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 128, condition: "fair", price: 240)
Product.create(model: 'iPhone 6 Plus', carrier: "T-Mobile", capacity: 128, condition: "pristine", price: 270)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 128, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 128, condition: "fair", price: 240)
Product.create(model: 'iPhone 6 Plus', carrier: "Sprint", capacity: 128, condition: "pristine", price: 270)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 128, condition: "busted", price: 160)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 128, condition: "fair", price: 300)
Product.create(model: 'iPhone 6 Plus', carrier: "Unlocked", capacity: 128, condition: "pristine", price: 335)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 128, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 128, condition: "fair", price: 260)
Product.create(model: 'iPhone 6', carrier: "ATT", capacity: 128, condition: "pristine", price: 290)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 128, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 128, condition: "fair", price: 270)
Product.create(model: 'iPhone 6', carrier: "Verizon", capacity: 128, condition: "pristine", price: 300)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 128, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 128, condition: "fair", price: 200)
Product.create(model: 'iPhone 6', carrier: "T-Mobile", capacity: 128, condition: "pristine", price: 225)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 128, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 128, condition: "fair", price: 200)
Product.create(model: 'iPhone 6', carrier: "Sprint", capacity: 128, condition: "pristine", price: 225)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 128, condition: "busted", price: 135)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 128, condition: "fair", price: 270)
Product.create(model: 'iPhone 6', carrier: "Unlocked", capacity: 128, condition: "pristine", price: 300)


